---
title: "Homework"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Handing in

Send your homework before the homework date to [martin.hinz\@unibe.ch](mailto:martin.hinz@unibe.ch).

+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| Homework                                                                                                                | Homework Date | Homework Data                                                                                                                      |
+=========================================================================================================================+===============+====================================================================================================================================+
| -   Style the polygons however you’d like                                                                               | 01.10.24      | [polygons.gpkg](https://github.com/BernCoDALab/gia/raw/main/lectures/01/data/polygons.gpkg)                                        |
|                                                                                                                         |               |                                                                                                                                    |
| -   Change the outline color or add a pattern                                                                           |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Style the labels                                                                                                    |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Change the font, the font size, or other attributes                                                                 |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me a screenshot                                                                                                |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Add the files you can download from the homework page to QGIS (note: the projection epsg is in the filename)        | 08.10.24      | [background_4326.tif](https://github.com/BernCoDALab/gia/raw/main/lectures/02/data/background_4326.tif)                            |
|     -   background_4326.tif                                                                                             |               |                                                                                                                                    |
|     -   cities_2056.csv                                                                                                 |               | [cities_2056.csv](https://github.com/BernCoDALab/gia/raw/main/lectures/02/data/cities_2056.csv)                                    |
|     -   lakes_3857.gpkg                                                                                                 |               |                                                                                                                                    |
| -   Style as you like                                                                                                   |               | [lakes_3857.gpkg](https://github.com/BernCoDALab/gia/raw/main/lectures/02/data/lakes_3857.gpkg)                                    |
| -   Send me a screenshot                                                                                                |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Filter for service requests in your borough                                                                         | 15.10.24      | [going_out_in_bern.zip](https://github.com/BernCoDALab/gia/raw/main/lectures/03/data/going_out_in_bern.zip)                        |
|                                                                                                                         |               |                                                                                                                                    |
|     -   Try and find something interesting                                                                              |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Change the style of the point, either to a different shape, color, or icon                                          |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Export your selection as a new shapefile                                                                            |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Get a background map                                                                                                |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Make a decent Map                                                                                                   |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me an exported map (png or pdf) and the exported shapefile (all the files that make up the shapefile)          |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Select an arbitrary map from archaeological literature (individual burial ground to europe wide mapping).           | 22.10.24      | no data necessary                                                                                                                  |
| -   Digitise the information (point or polygon)                                                                         |               |                                                                                                                                    |
| -   Send me the resulting shapefile/geopackage and the (georeferenced) original map.                                    |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Get the north and the south part of the Kanton of Bern                                                              | 30.10.24      | [kreise_bern_nord.zip](https://github.com/BernCoDALab/gia/raw/main/lectures/05/data/kreise_bern_nord.zip)                          |
| -   Unite them to get a map of the whole Kanton                                                                         |               |                                                                                                                                    |
| -   Get the Location of archaeological sites of the Kanton of Bern                                                      |               | [kreise_bern_sued.zip](https://github.com/BernCoDALab/gia/raw/main/lectures/05/data/kreise_bern_sued.zip)                          |
| -   Count the number of sites in each 'Amtsbezirk'                                                                      |               |                                                                                                                                    |
| -   Make a Map showing the number of sites color coded                                                                  |               | [fundstellen_bern.zip](https://github.com/BernCoDALab/gia/raw/main/lectures/05/data/fundstellen_bern.zip)                          |
| -   Send me the map                                                                                                     |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Select a arbitray point layer (the more archaeological the better)                                                  | 13.11.24      | no data necessary                                                                                                                  |
| -   Make a heatmap                                                                                                      |               |                                                                                                                                    |
| -   Conduct a Nearest Neighbor Analysis                                                                                 |               |                                                                                                                                    |
| -   Send me the shapefile of the points, a map of the resulting heatmap and the result of the Nearest Neighbor Analysis |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Get the archaeological sites of the Kanton bern with elevation (field: altitude1)                                   | 20.11.24      | [archaeological sites of the Kanton bern](https://github.com/BernCoDALab/gia/raw/main/lectures/07/data/fundstellen_mit_hoehen.zip) |
|                                                                                                                         |               |                                                                                                                                    |
| -   try out different interpolation algorithms                                                                          |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Which algorithm gives the best result for interpolation of elevation?                                               |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me your assessement and the best result via email (martin.hinz\@iaw.unibe.ch) as screenshot or exported map    |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Get the SRTM data from Ireland                                                                                      | 04.12.24      | no data necessary                                                                                                                  |
|                                                                                                                         |               |                                                                                                                                    |
| -   calculate the TPI                                                                                                   |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   send me a screen shot                                                                                               |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Select two locations of your choice (in Switzerland or the world)                                                   | 11.04.24      | no data necessary (download yourself)                                                                                              |
|                                                                                                                         |               |                                                                                                                                    |
| -   Calculate the least cost path between them                                                                          |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me a screenshot                                                                                                |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Select a locations of your choice (in Switzerland or the world)                                                     | 18.04.2024    | no data necessary (download yourself)                                                                                              |
|                                                                                                                         |               |                                                                                                                                    |
| -   Get the DEM from SRTM                                                                                               |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Calculate the 1h Catchment                                                                                          |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Evaluate a parameter of your choice in terms of the percentage of the catchment (slope is probably the easiest…)    |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me a screenshot                                                                                                |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| -   Get a DEM of a location of your choice (tip: make it not too big! And have it in projected coordinate/meter based)  | 16.02.2025    | no data necessary (download yourself)                                                                                              |
|                                                                                                                         |               |                                                                                                                                    |
| -   Make a vector point layer with one position in the landscape                                                        |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Make a viewpoint layer from it                                                                                      |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Calculate a viewshed from it                                                                                        |               |                                                                                                                                    |
|                                                                                                                         |               |                                                                                                                                    |
| -   Send me a screenshot of the result                                                                                  |               |                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
